soap_url: 'https://speller.yandex.net/services/spellservice?WSDL'

login: ' https://test-stand.gb.ru/gateway/login'
posts: 'https://test-stand.gb.ru/api/posts'

user: 'lem'
pas: '45e9ed6893'

post_desc: 'Описани'
post_test_desc: 'Test desc'

address: https://test-stand.gb.ru/
browser: chrome
sleep_time: 1